apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  conn-string: <base64-encoded-connection-string>

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  ext-api-key: <base64-encoded-api-key>
